on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"

      - run: uv sync --frozen

      - run: mkdocs build

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@v1.1.1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "bgm.tv"
          # Optional inputs with their defaults:
          source_dir: "public"
          target_dir: "/"
