on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          activate-environment: "true"

      - run: uv sync --frozen

      - run: zensical build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: "${{ github.token }}"
          publish_dir: ./public/
