on:
  push:
    branches:
      - master


jobs:
  build:
    permissions:
      contents: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'
          cache: pip

      - run: pip install -r requirements.txt

      - run: mkdocs build

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@cfc4b36780804138fc0df64d8e862ed28db7fd34 # v1.1.1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'bgm.tv'
          # Optional inputs with their defaults:
          source_dir: 'public'
          target_dir: '/'
